development:
  adapter: postgresql
  encoding: unicode
  database: job_portal_dev
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: job_portal_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: job_portal_prod
  pool: 5
  username: postgres
  password: postgres
